name: MdView
options:
  bundleIdPrefix: com.lysandre
targets:
  MdView:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: MdView/Sources
        excludes:
          - "**/*.md"
    resources:
      - path: MdView/Sources/marked.min.js
      - path: MdView/Sources/katex.min.js
      - path: MdView/Sources/katex.min.css
      - path: MdView/Sources/auto-render.min.js
      - path: MdView/Sources/highlight.min.js
      - path: MdView/Sources/highlight-github.min.css
      - path: MdView/Sources/highlight-github-dark.min.css
      - path: MdView/Sources/katex-fonts
    dependencies:
      - target: MdViewQuickLook
        embed: true
    info:
      path: MdView/Info.plist
    settings:
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

  MdViewQuickLook:
    type: app-extension
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: MdViewQuickLook/Sources
    resources:
      - path: MdView/Sources/marked.min.js
      - path: MdView/Sources/katex.min.js
      - path: MdView/Sources/katex.min.css
      - path: MdView/Sources/highlight.min.js
      - path: MdView/Sources/highlight-github.min.css
      - path: MdView/Sources/highlight-github-dark.min.css
      - path: MdView/Sources/katex-fonts
    info:
      path: MdViewQuickLook/Info.plist
    settings:
      SKIP_INSTALL: YES
